# Docker PostgreSQL database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/meal_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}
